# Generated by Copilot on 2026-04-06
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0002_auto_20230503_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='top_news',
            field=models.BooleanField(default=False, help_text='Display this item first on the news landing page'),
        ),
    ]
