# Generated by Django 6.0.2 on 2026-04-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0004_advertisementbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('Feedback / Suggestions', 'Feedback / Suggestions'), ('Sales', 'Sales'), ('Customer Care', 'Customer Care')], max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=256)),
                ('organisation', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscribeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=50)),
                ('subscription_type', models.CharField(choices=[('0', 'No Thanks'), ('1 Year', '1 Year'), ('2 Years', '2 Years')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
