# Generated by Django 6.0.2 on 2026-04-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0003_news_top_news'),
        ('epcandiapp', '0005_contactform_subscribeform'),
    ]

    operations = [
    ]
