# Generated by Django 6.0.2 on 2026-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0008_seed_site_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
                'ordering': ['-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvertisePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertise Page',
                'verbose_name_plural': 'Advertise Page',
                'ordering': ['-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalogs Page',
                'verbose_name_plural': 'Catalogs Page',
                'ordering': ['-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisclaimerPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disclaimer Page',
                'verbose_name_plural': 'Disclaimer Page',
                'ordering': ['-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jobs Page',
                'verbose_name_plural': 'Jobs Page',
                'ordering': ['-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaKitPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Kit Page',
                'verbose_name_plural': 'Media Kit Page',
                'ordering': ['-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Page',
                'verbose_name_plural': 'Privacy Page',
                'ordering': ['-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shopping Cart Page',
                'verbose_name_plural': 'Shopping Cart Page',
                'ordering': ['-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TendersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenders Page',
                'verbose_name_plural': 'Tenders Page',
                'ordering': ['-updated_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='advertisementbanner',
            options={'ordering': ['display_order', 'id'], 'verbose_name': 'Advertisement Banner', 'verbose_name_plural': 'Advertisement Banners'},
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Form', 'verbose_name_plural': 'Contact Forms'},
        ),
        migrations.AlterModelOptions(
            name='equipment_news',
            options={'verbose_name': 'Equipment News', 'verbose_name_plural': 'Equipment News'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='interview',
            options={'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='subscribeform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Subscribe Form', 'verbose_name_plural': 'Subscribe Forms'},
        ),
    ]
