# Generated by Django 6.0.2 on 2026-04-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0010_copy_sitepage_data_to_page_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitePage',
        ),
    ]
