# Generated by Django 6.0.2 on 2026-04-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0011_delete_sitepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvertisePage',
        ),
        migrations.DeleteModel(
            name='CatalogsPage',
        ),
        migrations.DeleteModel(
            name='JobsPage',
        ),
        migrations.DeleteModel(
            name='MediaKitPage',
        ),
        migrations.DeleteModel(
            name='TendersPage',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='query_type',
            field=models.CharField(choices=[('Feedback / Suggestions', 'Feedback / Suggestions'), ('Sales', 'Sales'), ('Customer Care', 'Customer Care'), ('Advertise', 'Advertise')], max_length=100),
        ),
    ]
