# Generated by Copilot on 2026-04-07

from django.db import migrations


def normalize_pagecontent_titles(apps, schema_editor):
    page_updates = {
        "AboutPage": {"title": "About", "heading": "ABOUT"},
        "DisclaimerPage": {"title": "Disclaimer", "heading": "DISCLAIMER"},
        "PrivacyPage": {"title": "Privacy", "heading": "PRIVACY"},
        "ShoppingCartPage": {"title": "Shopping Cart", "heading": "SHOPPING CART"},
    }

    for model_name, updates in page_updates.items():
        Model = apps.get_model("epcandiapp", model_name)
        page = Model.objects.order_by("id").first()
        if page is None:
            Model.objects.create(
                title=updates["title"],
                heading=updates["heading"],
                content="Content will be added soon.",
                is_published=True,
            )
            continue
        for field, value in updates.items():
            setattr(page, field, value)
        page.save(update_fields=["title", "heading"])


def reverse_normalize_pagecontent_titles(apps, schema_editor):
    page_updates = {
        "AboutPage": {"title": "ABOUT EPC&I", "heading": "ABOUT US"},
        "DisclaimerPage": {"title": "EPC&I DISCLAIMER", "heading": "DISCLAIMER"},
        "PrivacyPage": {"title": "EPC&I PRIVACY", "heading": "PRIVACY"},
        "ShoppingCartPage": {"title": "EPC&I SHOPPING CART", "heading": "SHOPPING CART"},
    }

    for model_name, updates in page_updates.items():
        Model = apps.get_model("epcandiapp", model_name)
        page = Model.objects.order_by("id").first()
        if page is None:
            continue
        for field, value in updates.items():
            setattr(page, field, value)
        page.save(update_fields=["title", "heading"])


class Migration(migrations.Migration):

    dependencies = [
        ("epcandiapp", "0012_delete_advertisepage_delete_catalogspage_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_pagecontent_titles, reverse_normalize_pagecontent_titles),
    ]
