# Generated by Django 6.0.4 on 2026-04-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0016_refactor_content_model_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('shopping_cart', models.TextField()),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Cart',
            },
        ),
        migrations.CreateModel(
            name='SquareFoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('square_foot', models.TextField()),
            ],
            options={
                'verbose_name': 'Square Foot',
                'verbose_name_plural': 'Square Foot',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='disclaimerpage',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Disclaimer', 'verbose_name_plural': 'Disclaimer'},
        ),
        migrations.AlterModelOptions(
            name='privacypage',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Privacy', 'verbose_name_plural': 'Privacy'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartpage',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Shopping Cart', 'verbose_name_plural': 'Shopping Cart'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='focus',
            name='category',
            field=models.CharField(choices=[('A', 'Aviation'), ('C', 'Cement'), ('I', 'Infrastructure'), ('IT', 'IT and Telecom'), ('O', 'Oil and Gas'), ('P', 'Power'), ('R', 'Real Estate')], default='I', max_length=200),
        ),
    ]
