# Generated by Django 6.0.4 on 2026-04-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0018_events_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, unique=True)),
                ('anonymized_ip', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics User',
                'verbose_name_plural': 'Analytics Users',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AlterField(
            model_name='subscribeform',
            name='subscription_type',
            field=models.CharField(choices=[('0', 'No Thanks'), ('print_1y', 'Print - 1 Year (12 Issues) - Rs. 1,920'), ('print_2y', 'Print - 2 Years (24 Issues) - Rs. 3,400'), ('print_3y', 'Print - 3 Years (36 Issues) - Rs. 5,000'), ('soft_1y', 'Soft Copy - 1 Year (12 Issues) - Rs. 500'), ('soft_2y', 'Soft Copy - 2 Years (24 Issues) - Rs. 1,000'), ('soft_3y', 'Soft Copy - 3 Years (36 Issues) - Rs. 1,500'), ('1 Year', 'Legacy - 1 Year'), ('2 Years', 'Legacy - 2 Years')], max_length=50),
        ),
        migrations.CreateModel(
            name='AnalyticsSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('entry_page', models.CharField(blank=True, max_length=400)),
                ('exit_page', models.CharField(blank=True, max_length=400)),
                ('referrer', models.CharField(blank=True, max_length=400)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_bounced', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='epcandiapp.analyticsuser')),
            ],
            options={
                'verbose_name': 'Analytics Session',
                'verbose_name_plural': 'Analytics Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('page_url', models.CharField(blank=True, max_length=400)),
                ('referrer', models.CharField(blank=True, max_length=400)),
                ('event_name', models.CharField(blank=True, max_length=120)),
                ('metadata_json', models.TextField(blank=True, default='{}')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('scroll_depth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ttfb_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('lcp_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('fid_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('cls', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='epcandiapp.analyticssession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='epcandiapp.analyticsuser')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
