# Generated by Django 6.0.4 on 2026-04-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0019_analyticsuser_alter_subscribeform_subscription_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCartPage',
        ),
    ]
