# Generated by Django 6.0.4 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0020_delete_shoppingcartpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter only the message part after "LATEST ISSUE -"', max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='latest_issues/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Latest Issue',
                'verbose_name_plural': 'Latest Issue',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
