# Generated by Django 6.0.4 on 2026-04-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0021_latestissue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertisementBanner',
            new_name='RightAdvertisement',
        ),
        migrations.AlterModelOptions(
            name='rightadvertisement',
            options={
                'ordering': ['display_order', 'id'],
                'verbose_name': 'RIGHT ADVERTISMENT',
                'verbose_name_plural': 'RIGHT ADVERTISMENT',
            },
        ),
        migrations.CreateModel(
            name='LeftAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='left_advertisement_banners/')),
                ('link', models.URLField(help_text='Company URL opened when users click this banner')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LEFT ADVERTISMENT',
                'verbose_name_plural': 'LEFT ADVERTISMENT',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
