# Generated by Django 6.0.4 on 2026-04-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0022_rightadvertisement_leftadvertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(help_text='Use an image sized exactly 468x60 pixels.', upload_to='banner_advertisement_banners/')),
                ('link', models.URLField(help_text='Company URL opened when users click this banner')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner Advertisment',
                'verbose_name_plural': 'Banner Advertisment',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
