# Generated by Django 6.0.4 on 2026-04-23 10:37

from django.db import migrations, models


def normalize_focus_categories(apps, schema_editor):
    Focus = apps.get_model('epcandiapp', 'Focus')
    mapping = {
        'A': 'Aviation',
        'C': 'Cement',
        'I': 'Infrastructure',
        'IT': 'IT and Telecom',
        'O': 'Oil and Gas',
        'P': 'Power',
        'R': 'Real Estate',
    }
    for old_value, new_value in mapping.items():
        Focus.objects.filter(category=old_value).update(category=new_value)


def noop_reverse(apps, schema_editor):
    # Keep reverse migration data-safe because custom categories are now allowed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0024_news_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='category',
            field=models.CharField(default='Infrastructure', max_length=200),
        ),
        migrations.RunPython(normalize_focus_categories, noop_reverse),
    ]
