# Generated by Django 6.0.4 on 2026-04-23 10:44

from django.db import migrations, models


def relabel_focus_categories(apps, schema_editor):
    Focus = apps.get_model('epcandiapp', 'Focus')

    current_categories = list(
        Focus.objects.exclude(category__isnull=True)
        .exclude(category__exact='')
        .values_list('category', flat=True)
        .distinct()
        .order_by('category')
    )

    for index, old_name in enumerate(current_categories, start=1):
        Focus.objects.filter(category=old_name).update(category=f'Category {index}')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('epcandiapp', '0025_alter_focus_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='category',
            field=models.CharField(default='Category 1', max_length=200),
        ),
        migrations.RunPython(relabel_focus_categories, noop_reverse),
    ]
